/* =========================================================================
   AdFyrr — Meta Pixel
   -------------------------------------------------------------------------
   Loaded on the funnel pages (sales, checkout, thank-you). The Pixel ID is
   public by design — it is visible in any page's source — so it lives here
   rather than in an environment variable.

   Events fired:
     PageView          every page (automatic)
     ViewContent       sales page
     InitiateCheckout  checkout page load
     AddPaymentInfo    when the buyer clicks Pay
     Purchase          thank-you page, with the real amount paid

   Purchase carries an eventID generated by the server at verification time.
   If Conversions API is added later, send the SAME eventID from the server and
   Meta will deduplicate the two. Without that, every sale is counted twice.
   ========================================================================= */
(function () {
  'use strict';

  /* ---- CONFIG -----------------------------------------------------------
     Replace with your Pixel ID from Meta Events Manager → Data Sources.
     Leave as-is and the pixel stays inert — nothing is sent. */
  var PIXEL_ID = '1788233318576373';

  var CONTENT = {
    content_ids: ['1300-orders-playbook'],
    content_name: '0 to 1300 Orders A Day — Meta Ads Playbook',
    content_type: 'product',
    content_category: 'Digital product'
  };

  var configured = /^\d{6,}$/.test(PIXEL_ID);
  if (!configured) {
    if (window.console) console.warn('Meta Pixel: PIXEL_ID not set in js/pixel.js — tracking disabled.');
    window.adfyrrTrack = function () {};
    return;
  }

  /* ---- standard Meta bootstrap ---- */
  !function (f, b, e, v, n, t, s) {
    if (f.fbq) return; n = f.fbq = function () {
      n.callMethod ? n.callMethod.apply(n, arguments) : n.queue.push(arguments);
    };
    if (!f._fbq) f._fbq = n;
    n.push = n; n.loaded = !0; n.version = '2.0'; n.queue = [];
    t = b.createElement(e); t.async = !0; t.src = v;
    s = b.getElementsByTagName(e)[0]; s.parentNode.insertBefore(t, s);
  }(window, document, 'script', 'https://connect.facebook.net/en_US/fbevents.js');

  window.fbq('init', PIXEL_ID);
  window.fbq('track', 'PageView');

  /**
   * Fire a standard event.
   * @param {string} name    e.g. 'Purchase'
   * @param {object} params  extra params (value, currency, …)
   * @param {string} eventId optional — required for CAPI deduplication
   */
  window.adfyrrTrack = function (name, params, eventId) {
    var data = {};
    var k;
    for (k in CONTENT) if (CONTENT.hasOwnProperty(k)) data[k] = CONTENT[k];
    if (params) for (k in params) if (params.hasOwnProperty(k)) data[k] = params[k];
    if (eventId) window.fbq('track', name, data, { eventID: eventId });
    else window.fbq('track', name, data);
  };

  /* ---- per-page events, driven by a data attribute on <body> ---- */
  var page = document.body && document.body.getAttribute('data-pixel-page');

  if (page === 'sales') {
    window.adfyrrTrack('ViewContent', { value: 299, currency: 'INR' });
  }

  if (page === 'checkout') {
    window.adfyrrTrack('InitiateCheckout', { value: 249, currency: 'INR', num_items: 1 });
  }

  if (page === 'thankyou') {
    /* Fire Purchase once per payment. A refresh must not count a second sale. */
    var receipt = null;
    try { receipt = JSON.parse(sessionStorage.getItem('adfyrr_pb1300_receipt') || 'null'); } catch (e) {}

    if (receipt && receipt.paymentId) {
      var firedKey = 'adfyrr_pb1300_purchase_fired';
      var already = false;
      try { already = sessionStorage.getItem(firedKey) === receipt.paymentId; } catch (e) {}

      if (!already) {
        window.adfyrrTrack('Purchase', {
          value: typeof receipt.amount === 'number' ? receipt.amount / 100 : 249,
          currency: 'INR',
          num_items: 1
        }, receipt.eventId || receipt.paymentId);
        try { sessionStorage.setItem(firedKey, receipt.paymentId); } catch (e) {}
      }
    }
  }
})();
